Features: SearchAfter、Term Aggregation Order、Aggregation  Include Filter Values
aquasecurity/esquery pull request #14
Opened 2021-03-13 03:06 UTC by hardy4yooz

Add some features base on https://github.com/aquasecurity/esquery/pull/12

SearchAfter:  https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#search-after
Term Aggregation Order: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-order
Aggregation Include Filter:https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_filtering_values_4

2021-03-14 07:57 UTC, oranmoshai commented
Thank you for the contribute :) all looks good i merged first #12 will you fix the conflict ?

2021-03-15 02:24 UTC, hardy4yooz commented
> Thank you for the contribute :) all looks good i merged first #12 will you fix the conflict ?

OK. I will fix it.

2021-03-15 07:20 UTC, oranmoshai requested changes

2021-03-15 07:20 UTC, oranmoshai commented on go.mod
> +module github.com/hardy4yooz/esquery
Please change to aquasecurity 
```suggestion
module github.com/aquasecurity/esquery
```

2021-03-15 07:29 UTC, hardy4yooz commented on go.mod
> +module github.com/hardy4yooz/esquery
yes,that is.

2021-03-15 07:43 UTC, merged